// src/components/route.component.jsx
import React from 'react';

export function Route(props) {
    return (
        <svg height="210" width="200" viewBox={calculateViewBox(props.points)} xmlns="http://www.w3.org/2000/svg">
            <polyline 
              points={props.points.path}
              style={{fill:'none', stroke:'orangered', strokeWidth: '0.0001'}} />
        </svg>
    )

    function calculateViewBox(route) {
        return [route.x, route.y, route.width, route.height].join(' ');
    }
}

// angular/src/app/route/route.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-route',
  templateUrl: './route.component.html',
  styleUrls: ['./route.component.css']
})
export class RouteComponent implements OnInit {

  @Input()
  points: any;

  private viewBox;

  private svgStyle;

  constructor() { }

  ngOnInit() {
    this.viewBox = this.calculateViewBox(this.points.path);

    this.svgStyle = this.getStyle(this.points);
  }

  private calculateViewBox(route) {
    return [route.x, route.y, route.width, route.height].join(' ');
}

  private getStyle(points) {
    const lightBlue = '#00b1fa';
    const orangeRed = 'orangered';

    return {
        fill: 'none',
        stroke: points.isRace ? orangeRed : lightBlue,
        strokeWidth: '0.0001'
    };
  }
}

<svg height="200" width="190" [attr.viewBox]="viewBox" xmlns="http://www.w3.org/2000/svg">
  <polyline
  [attr.points]="points.path.path"
  [ngStyle]=svgStyle />
</svg>
