// angular/src/app/poster-footer/poster-footer.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Athlete } from '../model/athlete';

@Component({
  selector: 'app-poster-footer',
  templateUrl: './poster-footer.component.html',
  styleUrls: ['./poster-footer.component.css']
})
export class PosterFooterComponent implements OnInit {

  @Input()
  athlete: Athlete = new Athlete();

  constructor() { }

  ngOnInit() {
  }

}

<div class="poster-footer">
  <div class="athlete-data">
      <label class="athlete-label">Name</label>
      <div class="athlete-value">{{ athlete.name }}</div>
  </div>
  <div class="athlete-data">
      <label class="athlete-label">Total Distance</label>
      <div class="athlete-value">{{ athlete.distance }}km</div>
  </div>
  <div class="athlete-data">
      <label class="athlete-label">Total time</label>
      <div class="athlete-value">{{ athlete.time }}h</div>
  </div>
</div>

// src/components/poster-footer.jsx
import React from 'react';
import './poster-footer.css';

export function PosterFooter(props) {
    return (
        <div className="poster-footer">
            <div className="athlete-data">
                <label className="athlete-label">Name</label>
                <div className="athlete-value">{ props.athlete.name }</div>
            </div>
            <div className="athlete-data">
                <label className="athlete-label">Total Distance</label>
                <div className="athlete-value">{ props.athlete.distance }</div>
            </div>
            <div className="athlete-data">
                <label className="athlete-label">Total time</label>
                <div className="athlete-value">{ props.athlete.time }</div>
            </div>
        </div>
    );
}

PosterFooter.defaultProps = {
    athlete: {}
};
